#!/usr/bin/env python
"""Check that two ETL data versions put every patient on the same side of the holdout.

The split is generated by ``create_patient_split`` from ``data_clinical_patient``'s
PATIENT_ID column *in file order*, with ``rng.choice`` over positional indices. It is
therefore stable across versions only if that file is stable. If a patient crosses the
boundary between versions, the holdout has leaked for any hypothesis compared across
them — which is exactly what a chain spanning two data versions does.

Usage:
    python scripts/check_split_stable.py <version_a> <version_b> [--data-base DIR]

Exits non-zero if any patient present in both versions changed split.
"""

import argparse
from pathlib import Path
import sys

import pandas as pd  # type: ignore

SPLIT_TABLE_FILENAME = "patient_split.parquet"


def _load(version_dir: Path) -> pd.Series:
    path = version_dir / SPLIT_TABLE_FILENAME
    if not path.exists():
        raise SystemExit(f"No {SPLIT_TABLE_FILENAME} in {version_dir}")
    df = pd.read_parquet(path)
    return df.set_index("PATIENT_ID")["split"]


def compare(a: pd.Series, b: pd.Series) -> pd.DataFrame:
    """Patients present in both whose split differs."""
    shared = a.index.intersection(b.index)
    moved = a.loc[shared] != b.loc[shared]
    return pd.DataFrame({"a": a.loc[shared][moved], "b": b.loc[shared][moved]})


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version_a")
    parser.add_argument("version_b")
    parser.add_argument(
        "--data-base", type=Path, default=Path.home() / "data" / "geryon_data"
    )
    args = parser.parse_args()

    base = args.data_base.expanduser()
    a = _load(base / args.version_a)
    b = _load(base / args.version_b)

    only_a = a.index.difference(b.index)
    only_b = b.index.difference(a.index)
    moved = compare(a, b)

    print(f"{args.version_a}: {len(a)} patients")
    print(f"{args.version_b}: {len(b)} patients")
    print(f"only in {args.version_a}: {len(only_a)}")
    print(f"only in {args.version_b}: {len(only_b)}")
    print(f"changed split: {len(moved)}")

    if len(moved):
        print("\nPatients that moved (first 20):")
        print(moved.head(20).to_string())
        print(
            "\nFAIL: the split is not stable across these versions. Cross-version "
            "comparisons within a chain are invalid until this is resolved."
        )
        return 1

    print("\nOK: every shared patient kept its split.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
